-- Customize Treesitter

---@type LazySpec
return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "bibtex",
      "c",
      "cmake",
      "cpp",
      "cuda",
      "dockerfile",
      "fish",
      "git_config",
      "git_rebase",
      "gitattributes",
      "gitcommit",
      "gitignore",
      "gnuplot",
      "jsdoc",
      "json",
      "latex",
      "llvm",
      "lua",
      "luadoc",
      "luap",
      "luau",
      "make",
      "markdown",
      "powershell",
      "pymanifest",
      "python",
      "ssh_config",
      "tmux",
      "toml",
      "vim",
      "vimdoc",
      "xml",
      "yaml",
      "zathurarc",
    },
    highlight = {
      enable = true,
      additional_vim_regex_highlighting = true,
    },
    indent = {
      enable = true,
    },
  },
}
